### ISSUE TITLE
Minimalizace zatížení tenzometru měřícího aerodynamický odpor

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/force_balance#11]
Aby byla minimalizována síla působící na uchycení tenzometru měřícího odpor, tak by bylo patrně vhodné aby, tento tenzometr byl přesunut doprostřed konstrukce.

K němu vedoucí táhlo by pak mělo být uchyceno co nejblíže úrovni rotoru. Tj. zhruba do oblasti na obrázku označené červeným puntíkem. 

![tensometer_configuration](https://user-images.githubusercontent.com/1194177/110254987-dc6c4280-7f91-11eb-8c2f-310d66f9d91f.png)

**Comment by roman-dvorak** [comment]
Ano, tohle by se mi také líbilo. Tenzometr bych nenechával na té tyči. Ale navrhoval bych ho zakomponovat přímo do toho středového dílu pod rotorem.

Z hlediska rozložení sil by to nemělo nic měnit táhlo a svislá tyč bude uložena ještě níže (dále od rotoru)

![20210309_114331.jpg](https://user-images.githubusercontent.com/5196729/110461911-56a2e100-80d0-11eb-8ecc-08fecf7b1920.jpg)
