### ISSUE TITLE
Vyvážení aerodynamické váhy 

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/force_balance#13]
Při konstrukci aerodynamické váhy je potřeba myslet na fakt, že aerodynamická váha bude muset být před měřením staticky vyvážena. 
Tj. po osazení měřeným rotorem bude potřeba vynulovat sílu působící na tenzometry. Zejména na tenzometr měřící vztlak. Tenzometr odporu bude při jízdě pravděpdobně víceméně jednosměrně zatížen. 

Navrhoval bych to vyřešit tak, že spoj vztlakový tenzometr-váha bude rozebírací. Například šroubem s křídlovou matkou.  Po montáži měřeného tenzometru na váhu se rozebere tento spoj. Čímže bude možné s váhou vertikálně hýbat a vidět silové působení  na pohyblivý horizontální díl. 

Na kratší stranu tohoto dílu bude pak nutné přidávat závaží do stavu, než dojde k vyvážení. Vzhledem k rozložení sil a délce pák v aktuální sestavě lze předpokládat, že tato přidaná hmotnost bude bohužel muset být poměrně velká v řádu kilogramů. 
Je tak otázka jaký materiál pro vyvážení zvolíme?

**Comment by taury55** [comment]
Návrh rozpojovacího spoje tenzometr vztlaku <-> střední základna se mi líbí.

Pro zmenšení hmotnosti potřebné k zatížení bych preferoval protažení jednoho z profilů viz. obrázek na jehož konec by se přidávali závaží.

![openscad_MLE9uAyME0](https://user-images.githubusercontent.com/33667517/110349199-c3679e00-8032-11eb-90a5-265be82c445d.png)

Pro materiál na závaží mi přijede nejlepší mít olověné granule nebo něco na ten způsob, které by se podle potřebného zatížení přisypaly do uzavíratelného zásobníku.

**Comment by kaklik** [comment]
Zajímavý nápad. Možná by protažení profilu nemuselo být ani tak dramatické, jak je zobrazeno na obrázku.  Případně by možná stačilo, že bude pohyblivý obdélníkový díl více protažen k přednímu tenzometru. Závaží by se tak dalo věšet přímo na profil ze spodní strany. 

Jako závaží se nám docela osvědčili wolframové řezné destičky. Mají ale nevýhodu, že se podobně jako třeba olověné kuličky sypou, čímž se mění pozice vyvážení. 

U dalekohledů se tenhle problém řeší tak, že se použije závaží o konstantní hmotnosti, případně pouze jen několik typů závaží a dalekohled se na montáži vyvažuje posouváním závaží po tyči. Na tyč se závaží zajišťuje utažením šroubu vedoucího skrz závaží. 

Co si o tomto způsobu vyvažování myslíte ostatní  @roman-dvorak  @slimonslimon ?

**Comment by slimonslimon** [comment]
toto koresponduje s představou, kterou jsem měl když jsi mi problém vyvážení připoměl.

**Comment by kaklik** [comment]
Prohlížel jsem si současnou implementaci řešení: 

![complete](https://user-images.githubusercontent.com/1194177/110999353-87a93d00-8380-11eb-80db-2ad6dd0c4c86.png)

A mám z toho dojem, že když bude to závaží takhle na tom jednom prodlouženém profilu, tak se to bude celé nepříjemně kroutit.  Nebylo by  lepší ty profily prodloužit oba a mezi ně dát další příčný profil, který by bylo možné posouvat i se závažím?

**Comment by roman-dvorak** [comment]
Připadá mi, že obecně je tam použito zbytečně moc profilů různých délek. Ten horní čtverec/obdélník by klidně mohl být z profilů jedné délky. Stejné by se použily i pro základnu a svislou tyč pro měření odporu. 

Jinak to vypadá o dost lépe.

**Comment by taury55** [comment]
Spodní základna je tvořena z 5 500mm profilů. Přední sloupek má 380mm v návrhu a v realu bude mít 390mm v rámci recyklace profilů staré váhy. Středová základna byla původně tvořena 300mm a 400mm profily, ale v rámci nové koncepce proti závaží by se mohli změnit na 500mm profily. Profil by se posunul dopředu a výsledná konstrukce by mohla vypadat takto:

![Inkedopenscad_oSnKLbAEsT_LI](https://user-images.githubusercontent.com/33667517/111002402-a827c600-8385-11eb-97c8-940d0b87a710.jpg)

**Comment by kaklik** [comment]
![image](https://user-images.githubusercontent.com/1194177/111197550-e52acd00-85be-11eb-8ee1-60430f476ca1.png)

Aktuální řešení  vypadá docela dobře :)  Jen možná hrozí, že se ten pohyblivý obdélník bude kroutit do vrtule. Tak jestli ještě nezvážit nějaké jeho možné budoucí vyztužení. 
Mě napadá tam případně přidat ještě jeden příčník dopředu, který by to zároveň mohl částečně vyvážit.

**Comment by kaklik** [comment]
Myslím že aktuální konstrukce je dostatečně tuhá, aby ke kroucení nedocházelo.
