### ISSUE TITLE
Airspeed measurement on an aerodynamic weight

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/force_balance#15]
@roman-dvorak  navrhuje airspeed měřit na dvou místech. 

1. Přímo na střeše měřícího auta - asi s použitím [WINDGAUGE03](https://github.com/mlab-modules/WINDGAUGE03)
2. Přímo na aerodynamické váze - zřejmě nějakou variantou [TFSLOT01](https://github.com/ThunderFly-aerospace/TFSLOT01), nebo [TFPIPE01](https://github.com/ThunderFly-aerospace/TFPIPE01)

S umístěním senzoru na aerodynamickou váhu vznikla komplikace, neboť s ním nebylo počítáno od začátku návrhu váhy. Možnost je buď snímač dát nahoru pod rotor na díl nad tenzometrem. 

Na obrázku označeno červeným čtvercem: 

![163746715_305092527706416_230559487652676863_n](https://user-images.githubusercontent.com/1194177/111919598-1279ee00-8a8b-11eb-8f21-3f349cb2b9bc.png)

**Comment by roman-dvorak** [comment]
Aby mohlo fungovat #10 (měření vibrací) z dat z IMU TFASPDIMU, tak je potřeba, aby připevňení airspeed senzoru bylo co nejblíže rotoru.

**Comment by kaklik** [comment]
> Aby mohlo fungovat #10 (měření vibrací) z dat z IMU TFASPDIMU, tak je potřeba, aby připevňení airspeed senzoru bylo co nejblíže rotoru.

Ten pokus s měřením vibrací bych asi nechal až na fázi, kdy to [TFASPDIMU](https://github.com/ThunderFly-aerospace/TFASPDIMU01) budem mít připojené na SPI. Do té doby si myslím, že v konstrukci té váhy vzniknout ještě další dosud neplánované změny. 

Spíš jako možný problém toho měření airspeed vidím [tohle](https://github.com/ThunderFly-aerospace/TFASPDIMU01/issues/5). Kdy ten snímač při zvýšené délce vodičů, která zrovna tady je potřeba, nebude fungovat.  

Možným řešením by byla realizace [I2C extenderu](https://github.com/ThunderFly-aerospace/Hardware/issues/23), který by kromě váhy mohl být i žádaným artiklem pro Pixhawk komunitu.

**Comment by kaklik** [comment]
Zatím bude vyřešeno snímačem TFSLOT přilepeným oboustrannou páskou.
