### ISSUE TITLE
Calibration device for weight calibration

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/force_balance#16]
Kalibrační přípravek by měl umožňovat snadnou kalibraci váhy v obou osách.

Představoval bych si to tak, že bude nějaký sloupek (jeřáb) který bude mít samonosnou základnu a to se postaví k váze (nebo do její konstrukce). Asi by bylo vhodné to vždy nějak moct zaaretovat aby to vždy bylo ve stejné poloze. Následně se provede kalibrace jedné osy a následně druhé. 

![20210329_091932.jpg](https://user-images.githubusercontent.com/5196729/112802512-8f502d80-9072-11eb-954a-6a5a1f585c90.jpg)
![20210329_091929.jpg](https://user-images.githubusercontent.com/5196729/112802839-f5d54b80-9072-11eb-9e6e-02a8bdbb6557.jpg)

**Comment by kaklik** [comment]
@taury55  tento problém vyřešil zatím jednoduchou kladkou namontovanou na vertikální sloupek  přední části váhy.  

Vzhledem k nedostatečné tuhosti vytištěného řešení, kterou by šlo sice zlepšit použitím žeber, ale stejně bude pro vyšší hmotnosti slabá. Tak by asi bylo lepší kladku předsadit před váhu pomocí hliníkového profilu, stejně jako jsou realizovány ostatní části váhy. 
Kladka by tak mohla držet na podstatně kratším a symetrickém 3D tištěném dílu, který by se nasunul na konec profilu přišroubovaného vodorovně na existující sloupek.

**Comment by kaklik** [comment]
Kalibrační kladka přidaná na váhu funguje
