### ISSUE TITLE
Zvýšení tuhosti konstrukce váhy

### ISSUE THREAD

**Issue by taury55** [ThunderFly-aerospace/force_balance#19]
Váha při v aktuální konstrukci není dostatečně tuhá vůči oscilacím ve směru jízdy, které rotor vytváří.
Je potřeba zpevnit přední sloupek úhlopříčným profilem a spojovací díl ramen vyztužit hliníkovým plechem (viz. obrázek 1 a 2).

![openscad_obqYjSnOH1](https://user-images.githubusercontent.com/33667517/116488358-7b2a6680-a892-11eb-80be-f33fa8a0598f.png)
Úhlopříčný profil (obr. 1)

![openscad_77a4Ovpfl6](https://user-images.githubusercontent.com/33667517/116488366-7ebded80-a892-11eb-9b4f-49464bf5c193.png)
Spojovací díl vyztužený plechem (obr. 2)

**Comment by kaklik** [comment]
> 
> ![openscad_77a4Ovpfl6](https://user-images.githubusercontent.com/33667517/116488366-7ebded80-a892-11eb-9b4f-49464bf5c193.png)
> Spojovací díl vyztužený plechem (obr. 2)

V tomhle místě bych spíše navrhoval místo připravit na vyřešení issue  #21 a  možná i #20.  Tím že se zde přidá další díl, který bude přišroubován k profilům z přední strany (skrz existující díl ve kterém jen přibydou otvory) a bude obsahovat vytištěná žebra, která zvýší tuhost.   Myslím že tohle řešení bude účinnější než plochý plech, který by musel být z velmi tvrdého materiálu, aby tuhost skutečně zvýšil.

**Comment by kaklik** [comment]
Vertikální sloupek jsem vyztužil úhlopříčnou stojinou z nerezového plechu viz foto.

![TFAEROSCALE](https://user-images.githubusercontent.com/1194177/121434797-20e6f000-c97e-11eb-8bce-c11e724d98c1.jpg)

Myslím že to takhle zatím celkem stačí.

**Comment by kaklik** [comment]
Aktuální tuhost je dostatečná.
