### ISSUE TITLE
Uchycení konstrukce váhy  na desku auta

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/force_balance#2]
Pro reálnné měření je potřeba vymyslet a nakreslit držák na testovací desku auta. Ideální by bylo, kdyby držák v maximální míře využíval existující otvory na desce. 

Zároveň je důležité, aby držák s celou váhou byl po sundání ze střechy samostatně stojící zařízení.

**Comment by raska-vilem** [comment]
takový díl už existuje https://github.com/ThunderFly-aerospace/TF-G1/blob/master/src/888_3007.scad. Akorát nevím do jaké míry ho bude třeba poupravit.

**Comment by kaklik** [comment]
Bude ho potřeba poupravit tak, aby jej bylo možné zaručeně použít. 

Přesuň ho prosím do tohoto repozitáře k váze v repozitáři TF-G1 už určitě není na nic potřeba.

**Comment by kaklik** [comment]
- [x] Upravit přesunutý model 888_3007.scad tak, aby horizontální hliníkový profil při uchycení na desku byl v úrovni desky (lze použít pouze dva šrouby pro montáž na střechu). Důvodem je, pak možnost opření delší části profilu o desku na autě. Tato úprava bude zřejmě potřebovat rozpůlení dílu na dvě symetrické poloviny které se našroubují na profil z každé strany.
- [x] díl upravit tak, aby k desce byl připevňován křídlovými maticemi na šrouby permanentně koukajícími nahoru z desky. (Tato úprava vyžaduje vytvoření plošek okolo šroubů, aby bylo možné se ke křídlové matici dostat)

**Comment by raska-vilem** [comment]
tak už jsem to poupravil, doufám že jsem ten druhý bod pochopil správně
