### ISSUE TITLE
Zvýšení pevnosti dílu pro montáž rotoru

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/force_balance#23]
Při testech došlo k odlomení držáku rotoru.

![20210824_155726](https://user-images.githubusercontent.com/1194177/130632664-c23044ec-a314-4a75-8488-2c84bde051dc.jpg)

Je potřeba navrhnout model se zaoblenější přechodovou hranou.

**Comment by kaklik** [comment]
@taury55 Navrhl model s novou konstrukcí přechodu. 

![image](https://user-images.githubusercontent.com/1194177/130632889-a37c5506-31ba-4623-b976-1a7cf571162b.png)

**Comment by kaklik** [comment]
Díl ale nejde vytisknout zřejmě kvůli manifold chybě v openscadu.
![image](https://user-images.githubusercontent.com/1194177/130635261-23d08f65-2019-4042-8a08-6bca9202f8e6.png)

**Comment by slimonslimon** [comment]
V jakém je tohle stavu?

**Comment by kaklik** [comment]
> V jakém je tohle stavu?

Myslím že je to vyřešený. Akorát jsme to od té doby netestovali.
