### ISSUE TITLE
Silová kalibrace aerodynamické váhy

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/force_balance#4]
Aktulální řešení kalibrace je zřejmě nedostatečné, neboť se provádí na moc vysoké úrovni a neuvažuje funkce samotného modulu BRIDGEADC.

**Comment by roman-dvorak** [comment]
@taury55 není s tím nějaký nový pokrok? Nebo je nějaká možnost, jak pomoct dořešení tohoto úkolu? 
Tahle záležitost by se totiž využila i pro další věci.

**Comment by slimonslimon** [comment]
Toto je ve fázi testování.

**Comment by kaklik** [comment]
Tahle část mi přijde vyřešená, teď je to asi hlavně o tom, jak kalibraci přiřadit reálné jednotky, ale to už je issue #16
