### ISSUE TITLE
Do základny vytvořit otvor pro matky a podložky šroubů

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/force_balance#5]
- [x] Vytvořit díry na podložku a matku
- [x] Umístit váhu excentricky

**1**
Do dílu 888_3007 udělat okolo děr pro šrouby pro připevnění na střechu otvor pro zapuštění matic, kterými jsou šrouby permanentně připevněny ke střeše. 

https://github.com/ThunderFly-aerospace/force_balance/blob/master/cad/STL/888_3007.stl

Nejlépe to vyřešit stejně jako je to tady:
https://github.com/ThunderFly-aerospace/TF-R1/blob/master/CAD/STL/888_4004.stl
Odtud lze opsat rozměr podložky a celkové velikosti otvoru.

**2**
Další věc, co mne napadá je, umístit váhu mírně excentricky a využít i přední a zadní šroub. Při přemontovávání plaformy zabere docela dost času tyto dva šrouby vytočit. Už jen z důvodu, že je pro to potřeba nějaký nástroj - klíč. 

Váhu by stačilo umístít o šířku hliníkových dílů na jednu stranu.

**Comment by kaklik** [comment]
V otvorech pouze chybí zaslepené vyrstvy umožňující tisk mostu a tím kvalitnější a pevnější výtisk.
