### ISSUE TITLE
Měření otáček rotoru během testu

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/force_balance#7]
Při měření rotoru na aerodynamické váze je potřeba měřit otáčky. 

Měření otáček by bylo možné realizovat několika způsoby: 

 * ~~hacknutím/rozluštěním komunikace [HiTec senzoru](https://hitecrcd.com/products/aircraft-radios-receivers-and-accessories/telemetry-systems-components/telemetry-components-/hts-orpm-optical-rpm-sensor/product) vyzkoušeno v [repozitáři orpm](https://github.com/ThunderFly-aerospace/orpm)~~
 * ~~Doplněním optického kotoučku a optozávory a použitím snímače [TFRPM01](https://github.com/ThunderFly-aerospace/TFRPM01)~~
 * ~~Přidáním magnetu a hallovy sondy v kombinaci s [TFRPM01](https://github.com/ThunderFly-aerospace/TFRPM01)~~
 * Montáží [TFPROBE](https://github.com/ThunderFly-aerospace/TFPROBE01) a připojením na [RTC03A](https://github.com/MLAB-project/Modules/tree/master/clock/RTC03A)

**Comment by taury55** [comment]
Po debatě s @roman-dvorak jsem vyrozuměl, že měření otáček se bude zaznamenávat stejným způsobem jako během letu a měření proto bude součástí rotorové konstrukce a není potřeba jej přidávat do konstrukce váhy.

Data ze senzoru bude zaznaménavát hardware a software váhy nebo se pro to bude využívat některé externí zařízení?

**Comment by kaklik** [comment]
Domnívám se že snímač otáček bude v aktuální implementaci realizovaný TFRPM senzorem připojeným na stejnou sběrnici I2C, jako budou připojené tenzometry. 
Celkově by tak celé zařízení mělo momentálně končit jedním USB kabelem do palubního počítače v autě. 
Je tedy pravda, že z hlediska váhy to příliš speciální úpravy nevyžaduje. Jen je potřeba držák rotoru. Upravit tak, aby do něj šel vložit snímač [TFPROBE](https://github.com/ThunderFly-aerospace/TFPROBE01).  Podobně, jako je to vyřešené na [rotorové hlavě TF-G2](https://github.com/ThunderFly-aerospace/TF-G2/blob/4s/CAD/stl/888_1012.stl), kde je snímač [TFPROBE zasunut do drážky z boku](https://github.com/ThunderFly-aerospace/TF-G2/issues/64#issuecomment-761890227).

**Comment by roman-dvorak** [comment]
Jo, souhlasím s @kaklik 


Rotor na sobě má pouze namontovanou rolničku s kotoučem na reflexní senzor. Ten má být správně umístěn v rotorovém adaptéru, což je součást platformy.

**Comment by kaklik** [comment]
Současné měření s použitím TFPROBE a TFRPM v principu funguje. Jen je potřeba doladit mechanické nedokonalosti adaptéru rotoru a vylepšit kabeláž. 
Vítek nakonec chce používat TFSLOT připojený do TFRPM, čímž se využije průchozí I2C sběrnice na TFRPM.
