### ISSUE TITLE
Zjistit, jestli existuje example v Arduinu

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/force_balance#8]
Bylo by dobré zjistit, jestli dneska existuje nějaký dostupný (arduino) example pro vyčítání převodníku, který obsahuje i interní kalibraci obvodem [AD7730l](https://www.analog.com/media/en/technical-documentation/data-sheets/AD7730_7730L.pdf)

Jedno z možných řešení je k ADpřevodníku připojit k arduino. Další možnost je přečíst si tento kód a implementovat to do pymlabu.

**Comment by kaklik** [comment]
Vzhledem k aktuálnímu SW pokroku, který provedl @slimonslimon se toto issue stává irelevantním.
