### ISSUE TITLE
Mechanical strengthening of the aerodynamic force balance 

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/force_balance#9]
Aktuální konstrukce váhy je velmi měkká. Má výrazné vůle do stran, což může způsobovat problémy nejen při měření. Váhu by bylo potřeba rozšířit tak, aby z této "2D" konstrukce se stala třírozměrná konstrukce, která bude v bočním směru pevná. Většina aktuálních dílů je moc pružná. Pokud budou znovu využity některé díly (např. držák tenzometru) tak by měl být zesílen. 

Můj návrh je tedy následovný:
![20210224_133522](https://user-images.githubusercontent.com/5196729/109002430-800e4680-76a6-11eb-93b8-c3bbd256210f.jpg)

Díky tomu, že to není plochá konstrukce, tak z toho lze docela těžit u řešení jednotlivých kloubů, kdy se dost rozšiřují možnosti jejich umístění. Nákres není nakreslený v měřítku a jednotlivé délky pák by mělo jít nastavovat. Aktuálně jsou k dispozici dva roměry profilových tyčí (360 mm a 320 mm), které lze používat na první prototpy. Následně pak asi půjde získat jiné délky a tím optimalizovat poměry sil. 

Bylo by užitečné aby k tomu existovala celková sestava, kde to bude vidět.

**Comment by kaklik** [comment]
@taury55  vytvořil již kompletní celkovou sestavu nové konstrukce: 

![complete](https://user-images.githubusercontent.com/1194177/110254518-ce1d2700-7f8f-11eb-9121-651ebace3810.png)
